name: Run-api-tests

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      test_results_path:
        required: true
        type: string
jobs:
  api-tests:      
      strategy:
        matrix:
          os: ${{fromJson(inputs.environment)}}  
        fail-fast: false

      name: Run API (${{ matrix.os }}) tests
      runs-on: ${{ matrix.os }}

      steps:
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: download workflow artifact
          env:
            WORKFLOW_NAME: CI.yml
            ARTIFACT_NAME: testing-artifact-api
            GH_TOKEN: ${{ env.GITHUB_TOKEN }}
          shell: bash
          run: |
            TEST_RUN_ID=$(gh run list --workflow ${{ env.WORKFLOW_NAME }} --json databaseId --jq '.[0]' | jq '.databaseId')
            gh run download ${{ env.TEST_RUN_ID }} -n ${{ env.ARTIFACT_NAME }} -D ./download
        - name: Run git init
          run: git init
        - name: Run tests
          run: dotnet test TestWare.Samples.API.dll --logger "trx;LogFileName=results.trx" --results-directory "${{ inputs.test_results_path }}"
        - name: Test Report
          uses: dorny/test-reporter@v1.6.0
          if: success() || failure()
          with:
            name: Report - API Tests - (${{ matrix.os }})
            path: ${{ inputs.test_results_path }}/results.trx
            reporter: dotnet-trx
